# Generated by Django 4.1.2 on 2022-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
