# Generated by Django 4.1.2 on 2022-10-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='the_song_lyric',
            new_name='the_song_title',
        ),
    ]
