# Generated by Django 4.1.2 on 2022-10-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_rename_the_song_lyric_lyric_the_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
